### ISSUE TITLE
A little curious about the complicity of allpath.m  

### ISSUE THREAD

**Issue by ruisonghan** [CTU-IIG/TORSCHE#4]
when trying to study the function **maxmulticommodityflow**, I noticed that you have used **allpath.m** to find all the paths. 

When the number of nodes is small, it is OK for the algorithms. However when the number is a little big, the algorithm will be not efficient and can't get a result in a polynomial time.  Do you have further plans to update your toolbox to try more heuristic algorithms?

**Comment by dvoraj57** [comment]
Hi,
To be honest, We stopped any development activities on TORSCHE some time ago because of the lack of  the workforce. We decided to put it to the github to make it open for everyone who wants to use it and possible even improve it. We know that there is necessary to spent a lot of time to rewrite it for new MATLAB 2015 but unfortunately we do not have resources (time) for it.
